<?php

use App\Question;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class QuestionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $question = new Question();
        $question->title = 'কারও পৌষ মাস, কারও ______।';
        $question->set_no = 1;
        $question->answer_text = '';
        $question->correct_answer = 'সর্বনাশ';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'কয়লা ধুইলে _____ যায় না।';
        $question->set_no = 1;
        $question->answer_text = '';
        $question->correct_answer = 'ময়লা';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'মেঘের কোলে রোদ হেসেছে, _____ গেছে টুটি।';
        $question->set_no = 1;
        $question->answer_text = '';
        $question->correct_answer = 'বাদল';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘হাট্টি মাটিম টিম’ এর পরের লাইন: _______________ ';
        $question->set_no = 1;
        $question->answer_text = '';
        $question->correct_answer = 'তারা মাঠে পাড়ে ডিম';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘আমাদের দেশে হবে সেই ছেলে কবে’ এর পরের লাইন কী?';
        $question->set_no = 1;
        $question->answer_text = '';
        $question->correct_answer = 'কথায় না বড় হয়ে কাজে বড় হবে';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক বানান কোনটি? ক. মুমূর্ষ   খ. মুমূর্ষু   গ. মূমুর্ষ';
        $question->set_no = 1;
        $question->answer_text = '';
        $question->correct_answer = 'মুমূর্ষু';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘শয্যা’ শব্দের অর্থ কী?';
        $question->set_no = 1;
        $question->answer_text = '';
        $question->correct_answer = 'বিছানা';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'বাংলা অক্ষরে লেখো: ami banglay gaan gai';
        $question->set_no = 1;
        $question->answer_text = '';
        $question->correct_answer = 'আমি বাংলায় গান গাই';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক বাংলায় লেখো: আই ছেলেরা আই মেয়েরা ফুল তুলিতে যায়';
        $question->set_no = 1;
        $question->answer_text = '';
        $question->correct_answer = 'আয় ছেলেরা আয় মেয়েরা ফুল তুলিতে যাই';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'কোনটি সঠিক? ক. সব ফুল   খ. সব ফুলগুলো   গ. সব ফুলসমূহ';
        $question->set_no = 1;
        $question->answer_text = '';
        $question->correct_answer = 'সব ফুল';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'অতি লোভে _____ নষ্ট।';
        $question->set_no = 2;
        $question->answer_text = '';
        $question->correct_answer = 'তাঁতি';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'ঢেঁকি ____ গেলেও ধান ভানে।';
        $question->set_no = 2;
        $question->answer_text = '';
        $question->correct_answer = 'স্বর্গে';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘ধন ধান্য পুষ্প ভরা’ এর পরের লাইন কী? ______________';
        $question->set_no = 2;
        $question->answer_text = '';
        $question->correct_answer = 'আমাদের এই বসুন্ধরা';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘একটা যদি পাই’ এর পরের লাইন: _______________ ';
        $question->set_no = 2;
        $question->answer_text = '';
        $question->correct_answer = 'অমনি ধরে গাপুস গুপুস খাই';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'আমরা যদি না জাগি মা __________?';
        $question->set_no = 2;
        $question->answer_text = '';
        $question->correct_answer = 'কেমনে সকাল হবে';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক বানান কোনটি? ক. মুহুর্ত   খ. মূহুর্ত  গ. মুহূর্ত';
        $question->set_no = 2;
        $question->answer_text = '';
        $question->correct_answer = 'মুহূর্ত';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘প্রত্যুৎপন্নমতি’ শব্দের অর্থ কী? ক. উপস্থিত বুদ্ধিযুক্ত   খ. উৎপন্নকারী  গ. অহংকারী';
        $question->set_no = 2;
        $question->answer_text = '';
        $question->correct_answer = 'উপস্থিত বুদ্ধিযুক্ত';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'বাংলা অক্ষরে লেখো: amra tomader bhulbo na';
        $question->set_no = 2;
        $question->answer_text = '';
        $question->correct_answer = 'আমরা তোমাদের ভুলবো না';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক বাংলায় লেখো: বিশ্বজোড়া পাঠশালা মোড় সবার আমি ছাএ';
        $question->set_no = 2;
        $question->answer_text = '';
        $question->correct_answer = 'বিশ্বজোড়া পাঠশালা মোর সবার আমি ছাত্র';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'কোনটি সঠিক? ক. খেলা চলাকালীন সময়ে  খ. খেলা চলাকালীন  গ. খেলা চলাকালীণ সময়ে';
        $question->set_no = 2;
        $question->answer_text = '';
        $question->correct_answer = 'খেলা চলাকালীন';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'নাচতে না জানলে _____।';
        $question->set_no = 3;
        $question->answer_text = '';
        $question->correct_answer = 'উঠান বাঁকা';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'চোর শোনে না _______।';
        $question->set_no = 3;
        $question->answer_text = '';
        $question->correct_answer = 'ধর্মের কাহিনী';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘আ-মরি বাংলা ভাষা’ এর আগের লাইন কী? ______________';
        $question->set_no = 3;
        $question->answer_text = '';
        $question->correct_answer = 'মোদের গরব, মোদের আশা';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘মারবো চাবুক চড়বো ঘোড়া’ এর আগের লাইন: _______________ ';
        $question->set_no = 3;
        $question->answer_text = '';
        $question->correct_answer = 'আম পাতা জোড়া জোড়া';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'বিশ্বজোড়া পাঠশালা মোর, __________?';
        $question->set_no = 3;
        $question->answer_text = '';
        $question->correct_answer = 'সবার আমি ছাত্র';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক বানান কোনটি? ক. নিড়বচ্ছিন্ন   খ. নিরবচ্ছিন্ন  গ. নিরবিচ্ছিন্ন';
        $question->set_no = 3;
        $question->answer_text = '';
        $question->correct_answer = 'নিরবিচ্ছিন্ন';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘বারি’ শব্দের অর্থ কী? ক. ঘর   খ. পানি  গ. আকাশ';
        $question->set_no = 3;
        $question->answer_text = '';
        $question->correct_answer = 'পানি';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'বাংলা অক্ষরে লেখো: ekti Bangladesh tumi jagroto jonotar';
        $question->set_no = 3;
        $question->answer_text = '';
        $question->correct_answer = 'একটি বাংলাদেশ তুমি জাগ্রত জনতার';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক বাংলায় লেখো: আই আই চাদ মামা টিপ দিয়ে যা';
        $question->set_no = 3;
        $question->answer_text = '';
        $question->correct_answer = 'আয় আয় চাঁদ মামা টিপ দিয়ে যা';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'কোনটি সঠিক? ক. সকল মানুষদের  খ. সকল মানুষেরা  গ. সকল মানুষ';
        $question->set_no = 3;
        $question->answer_text = '';
        $question->correct_answer = 'সকল মানুষ';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'ইট মারলে _____ খেতে হয়।';
        $question->set_no = 4;
        $question->answer_text = '';
        $question->correct_answer = 'পাটকেল';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '_____ ঘায়ে নুনের ছিটা।';
        $question->set_no = 4;
        $question->answer_text = '';
        $question->correct_answer = 'কাটা';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘মাঝে মাঝে তব দেখা পাই’ এর পরের লাইন কী? ______________';
        $question->set_no = 4;
        $question->answer_text = '';
        $question->correct_answer = 'চিরদিন কেন পাই না';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘কাঠবিড়ালি! কাঠবিড়ালি!’ এর পরের লাইন: _______________';
        $question->set_no = 4;
        $question->answer_text = '';
        $question->correct_answer = 'পেয়ারা তুমি খাও?';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '"ফুলের গন্ধে ঘুম আসে না"-এর পরের লাইন কী? _____ ';
        $question->set_no = 4;
        $question->answer_text = '';
        $question->correct_answer = 'একলা জেগে রই';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক বানান কোনটি? ক. বুদ্ধিজিবি খ. বুদ্ধিজীবী গ. বুদ্ধিজিবী';
        $question->set_no = 4;
        $question->answer_text = '';
        $question->correct_answer = 'বুদ্ধিজীবী';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘ললাট’ শব্দের অর্থ কী? ক. কপাল খ. নাক গ. আঙুল';
        $question->set_no = 4;
        $question->answer_text = '';
        $question->correct_answer = 'কপাল';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'বাংলা অক্ষরে লেখো: o amar desher mati tomar pore thekai matha';
        $question->set_no = 4;
        $question->answer_text = '';
        $question->correct_answer = 'ও আমার দেশের মাটি তোমার পরে ঠেকাই মাথা';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক বাংলায় লেখো: উদ্যোগ নিচ্ছে উওর ঢাকার ছাএসমাজ';
        $question->set_no = 4;
        $question->answer_text = '';
        $question->correct_answer = 'উদ্যোগ নিচ্ছে উত্তর ঢাকার ছাত্রসমাজ';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'কোনটি সঠিক? ক. অজস্র লোক   খ. অজস্র লোকজন   গ. অজস্র লোকবৃন্দ';
        $question->set_no = 4;
        $question->answer_text = '';
        $question->correct_answer = 'অজস্র লোক';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'আদার ব্যাপারি _____ খোঁজ।';
        $question->set_no = 5;
        $question->answer_text = '';
        $question->correct_answer = 'জাহাজের';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'খাল কেটে _____ আনা।';
        $question->set_no = 5;
        $question->answer_text = '';
        $question->correct_answer = 'কুমির';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘আমি চিনি গো চিনি তোমারে’ এর পরের লাইন কী? ______________';
        $question->set_no = 5;
        $question->answer_text = '';
        $question->correct_answer = 'ওগো বিদেশিনী';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘আয় বৃষ্টি ঝেঁপে’ এর পরের লাইন: _______________';
        $question->set_no = 5;
        $question->answer_text = '';
        $question->correct_answer = 'ধান দেবো মেপে';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '"আমাদের ছোট নদী চলে বাঁকে বাঁকে"-এর পরের লাইন কী?';
        $question->set_no = 5;
        $question->answer_text = '';
        $question->correct_answer = 'বৈশাখ মাসে তার হাঁটু জল থাকে';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক বানান কোনটি? ক. পিচাশ খ. পিশাচ গ. পিসাচ';
        $question->set_no = 5;
        $question->answer_text = '';
        $question->correct_answer = 'পিশাচ';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘মীন’ শব্দের অর্থ কী? ক. ব্যাঙ খ. মাছ গ. পাখি';
        $question->set_no = 5;
        $question->answer_text = '';
        $question->correct_answer = 'মাছ';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'বাংলা অক্ষরে লেখো: moder gorob moder asha a-mori bangla vasha';
        $question->set_no = 5;
        $question->answer_text = '';
        $question->correct_answer = 'মোদের গরব মোদের আশা আ-মরি বাংলা ভাষা';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক বাংলায় লেখো: আমি যা চায় তা ভুল করে চায়';
        $question->set_no = 5;
        $question->answer_text = '';
        $question->correct_answer = 'আমি যা চাই তা ভুল করে চাই';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'কোনটি সঠিক? ক. তুমিই কি রাজু?  খ. তুমিই কী রাজু?';
        $question->set_no = 5;
        $question->answer_text = '';
        $question->correct_answer = 'তুমিই কি রাজু?';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'অতি লোভে _____ নষ্ট।';
        $question->set_no = 6;
        $question->answer_text = '';
        $question->correct_answer = 'তাঁতি';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'ঝোপ বুঝে _____ মারা।';
        $question->set_no = 6;
        $question->answer_text = '';
        $question->correct_answer = 'কোপ';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘তোমার পরে ঠেকাই মাথা’ এর আগের লাইন কী? ______________';
        $question->set_no = 6;
        $question->answer_text = '';
        $question->correct_answer = 'ও আমার দেশের মাটি';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘রামগরুড়ের ছানা...’ এর পরের লাইন: _______________';
        $question->set_no = 6;
        $question->answer_text = '';
        $question->correct_answer = 'হাসতে তাদের মানা';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '"ভেঙে ফেল কর রে লোপাট" -এর আগের লাইন কী?';
        $question->set_no = 6;
        $question->answer_text = '';
        $question->correct_answer = 'কারার ঐ লৌহ কপাট';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক বানান কোনটি? ক. উর্ধ খ. ঊর্ধ্ব গ. ঊর্ধ';
        $question->set_no = 6;
        $question->answer_text = '';
        $question->correct_answer = 'ঊর্ধ্ব';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘সমাচার’ শব্দের অর্থ কী? ক. খবর খ. আচার গ. টক';
        $question->set_no = 6;
        $question->answer_text = '';
        $question->correct_answer = 'খবর';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'বাংলা অক্ষরে লেখো: mora ekti fulke bachabo bole judhdho kori';
        $question->set_no = 6;
        $question->answer_text = '';
        $question->correct_answer = 'মোরা একটি ফুলকে বাঁচাবো বলে যুদ্ধ করি';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক বাংলায় লেখো: আমি যা চায় তা পায় না';
        $question->set_no = 6;
        $question->answer_text = '';
        $question->correct_answer = 'আমি যা চাই তা পাই না';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'কোনটি সঠিক? ক. কী দিয়ে ভাত খেলে?  খ. কি দিয়ে ভাত খেলে?';
        $question->set_no = 6;
        $question->answer_text = '';
        $question->correct_answer = 'কী দিয়ে ভাত খেলে?';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'যত গর্জে _____ বর্ষে না।';
        $question->set_no = 7;
        $question->answer_text = '';
        $question->correct_answer = 'তত';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '_____ এসে তরী ডোবা।';
        $question->set_no = 7;
        $question->answer_text = '';
        $question->correct_answer = 'তীরে';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘ঊর্ধ্ব গগণে বাজে মাদল’ এর আগের লাইন কী? ______________';
        $question->set_no = 7;
        $question->answer_text = '';
        $question->correct_answer = 'চল চল চল';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘ঐখানেতে বাস করে কানা বগীর ছা’ এর আগের লাইন: _______________';
        $question->set_no = 7;
        $question->answer_text = '';
        $question->correct_answer = 'ঐ দেখা যায় তালগাছ ঐ আমাদের গাঁ';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '"রবিঠাকুরের অজর কবিতা, অবিনাশী গান" এর আগের লাইন কী?';
        $question->set_no = 7;
        $question->answer_text = '';
        $question->correct_answer = 'স্বাধীনতা তুমি';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক বানান কোনটি? ক. স্বাস্থ খ. স্বাস্ত গ. স্বাস্থ্য';
        $question->set_no = 7;
        $question->answer_text = '';
        $question->correct_answer = 'স্বাস্থ্য';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘প্রভাকর’ শব্দের অর্থ কী? ক. চাঁদ খ. জাদুকর গ. সূর্য';
        $question->set_no = 7;
        $question->answer_text = '';
        $question->correct_answer = 'সূর্য';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'বাংলা অক্ষরে লেখো: purbo digonte surjo utheche';
        $question->set_no = 7;
        $question->answer_text = '';
        $question->correct_answer = 'পূর্ব দিগন্তে সূর্য উঠেছে';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক বাংলায় লেখো: আমাদের লক্ষ বাঁধা এড়িয়ে দেশের উন্নতি';
        $question->set_no = 7;
        $question->answer_text = '';
        $question->correct_answer = 'আমাদের লক্ষ্য বাধা এড়িয়ে দেশের উন্নতি';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক কোনটি? ক. কি সুন্দর পাখি!  খ. কী সুন্দর পাখি!';
        $question->set_no = 7;
        $question->answer_text = '';
        $question->correct_answer = 'কী সুন্দর পাখি!';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সবুরে _____ ফলে।';
        $question->set_no = 8;
        $question->answer_text = '';
        $question->correct_answer = 'মেওয়া';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'জলে কুমির ডাঙায় _____';
        $question->set_no = 8;
        $question->answer_text = '';
        $question->correct_answer = 'বাঘ';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘পাগলা হাওয়ার বাদল-দিনে’ এর পরের লাইন কী? ______________';
        $question->set_no = 8;
        $question->answer_text = '';
        $question->correct_answer = 'পাগল আমার মন জেগে ওঠে';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘সবার আগে কুসুম-বাগে উঠব আমি ডাকি!’ এর আগের লাইন: _______________';
        $question->set_no = 8;
        $question->answer_text = '';
        $question->correct_answer = 'আমি হব সকাল বেলার পাখি';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '"জ্বলে পুড়ে মরে ছারখার, তবু মাথা নোয়াবার নয়" এর আগের লাইন কী?';
        $question->set_no = 8;
        $question->answer_text = '';
        $question->correct_answer = 'সাবাস বাংলাদেশ এ পৃথিবী অবাক তাকিয়ে রয়';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক বানান কোনটি? ক. প্রতিযোগী খ. প্রতিযোগি গ. প্রতিযগী';
        $question->set_no = 8;
        $question->answer_text = '';
        $question->correct_answer = 'প্রতিযোগী';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘কমল’ শব্দের অর্থ কী? ক. পদ্ম   খ. নরম  গ. গোলাপ';
        $question->set_no = 8;
        $question->answer_text = '';
        $question->correct_answer = 'পদ্ম';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'বাংলা অক্ষরে লেখো: somy gele sadhon hobe na';
        $question->set_no = 8;
        $question->answer_text = '';
        $question->correct_answer = 'সময় গেলে সাধন হবে না';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক বাংলায় লেখো: ১০০ টাকা মাএ';
        $question->set_no = 8;
        $question->answer_text = '';
        $question->correct_answer = '১০০ টাকা মাত্র';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'চলিত ভাষায় লেখো: তাহাকে হেথায় আসিতে দেখিলাম';
        $question->set_no = 8;
        $question->answer_text = '';
        $question->correct_answer = 'তাকে এখানে আসতে দেখলাম';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'নাচতে না জানলে _____।';
        $question->set_no = 9;
        $question->answer_text = '';
        $question->correct_answer = 'উঠান বাঁকা';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '_____ উপর খাড়ার ঘা।';
        $question->set_no = 9;
        $question->answer_text = '';
        $question->correct_answer = 'মরার';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '"সখী ভালোবাসা কারে কয়" এর পরের লাইন কী?';
        $question->set_no = 9;
        $question->answer_text = '';
        $question->correct_answer = 'সে কি কেবলই যাতনাময়';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '"ভোর হলো দোর খোল" এর পরের লাইন: _______________';
        $question->set_no = 9;
        $question->answer_text = '';
        $question->correct_answer = 'খুকুমণি ওঠো রে';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '"লঙ্ঘিতে হবে রাত্রি নিশীথে যাত্রীরা হুঁশিয়ার" এর আগের লাইন কী?';
        $question->set_no = 9;
        $question->answer_text = '';
        $question->correct_answer = 'দুর্গম গিরি কান্তার মরু';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক বানান কোনটি? ক. লন্ডন খ. লণ্ডন গ. লন্ডণ';
        $question->set_no = 9;
        $question->answer_text = '';
        $question->correct_answer = 'লন্ডন';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘গলদ’ শব্দের অর্থ কী? ক. ষাঁড় খ. ভুল গ. কাঁটা';
        $question->set_no = 9;
        $question->answer_text = '';
        $question->correct_answer = 'ভুল';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'বাংলা অক্ষরে লেখো: tomar bhoy nei ma amra protibad korte jani';
        $question->set_no = 9;
        $question->answer_text = '';
        $question->correct_answer = 'তোমার ভয় নেই মা আমরা প্রতিবাদ করতে জানি';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক বাংলায় লেখো: ছাএরা স্কুলে যাই';
        $question->set_no = 9;
        $question->answer_text = '';
        $question->correct_answer = 'ছাত্ররা স্কুলে যায়';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'চলিত ভাষায় লেখো: বৃক্ষে বৃক্ষে পুষ্প ফুটিয়াছে।';
        $question->set_no = 9;
        $question->answer_text = '';
        $question->correct_answer = 'গাছে গাছে ফুল ফুটেছে';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'ঘুঘু দেখেছো, _____ দেখোনি।';
        $question->set_no = 10;
        $question->answer_text = '';
        $question->correct_answer = 'ফাঁদ';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'শাক দিয়ে _____ ঢাকা।';
        $question->set_no = 10;
        $question->answer_text = '';
        $question->correct_answer = 'মাছ';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '"খাঁচার ভিতর অচিন পাখি" এর পরের লাইন কী?';
        $question->set_no = 10;
        $question->answer_text = '';
        $question->correct_answer = 'কেমনে আসে যায়';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '"আয় আয় চাঁদ মামা" এর পরের লাইন: _______________';
        $question->set_no = 10;
        $question->answer_text = '';
        $question->correct_answer = 'টিপ দিয়ে যা';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'মনে করো যেন বিদেশ ঘুরে ______ নিয়ে যাচ্ছি অনেক দূরে';
        $question->set_no = 10;
        $question->answer_text = '';
        $question->correct_answer = 'মাকে';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক বানান কোনটি? ক. পরিস্কার খ. পরীষ্কার গ. পরিষ্কার';
        $question->set_no = 10;
        $question->answer_text = '';
        $question->correct_answer = 'পরিষ্কার';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = '‘নৃপতি’ শব্দের অর্থ কী? ক. নাপিত খ. রাজা গ. প্রজা';
        $question->set_no = 10;
        $question->answer_text = '';
        $question->correct_answer = 'রাজা';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'বাংলা অক্ষরে লেখো: teerhara ei dhewer sagor pari dibo re';
        $question->set_no = 10;
        $question->answer_text = '';
        $question->correct_answer = 'তীরহারা এই ঢেউয়ের সাগর পাড়ি দেবো রে';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক বাংলায় লেখো: সৎ পাএ মানেই ভালো পাএ';
        $question->set_no = 10;
        $question->answer_text = '';
        $question->correct_answer = 'সৎ পাত্র মানেই ভালো পাত্র';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'চলিত ভাষায় লেখো: পারিব না এ কথাটি বলিও না আর';
        $question->set_no = 10;
        $question->answer_text = '';
        $question->correct_answer = 'পারবো না এ কথাটি বোলো না আর';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        // For testing purpose only
        $question = new Question();
        $question->title = 'বাংলা অক্ষরে লেখো: tomar bhoy nei ma amra protibad korte jani';
        $question->set_no = 60;
        $question->answer_text = '';
        $question->correct_answer = '123';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'সঠিক বাংলায় লেখো: ছাএরা স্কুলে যাই';
        $question->set_no = 60;
        $question->answer_text = '';
        $question->correct_answer = '123';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'চলিত ভাষায় লেখো: বৃক্ষে বৃক্ষে পুষ্প ফুটিয়াছে।';
        $question->set_no = 60;
        $question->answer_text = '';
        $question->correct_answer = '123';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'ঘুঘু দেখেছো, _____ দেখোনি।';
        $question->set_no = 60;
        $question->answer_text = '';
        $question->correct_answer = '123';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

        $question = new Question();
        $question->title = 'শাক দিয়ে _____ ঢাকা।';
        $question->set_no = 60;
        $question->answer_text = '';
        $question->correct_answer = '123';
        $question->year = 2020;
        $question->is_answer_visible = false;
        $question->created_by = 1;
        $question->updated_by = 1;
        $question->created_at = Carbon::now();
        $question->updated_at = Carbon::now();
        $question->save();

    }
}
